- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Update system
      apt:
        update_cache=yes
        
    - name: Install Apache
      apt: 
        name=apache2  
        state=latest
